# Generated by Django 6.0.1 on 2026-02-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
