# Generated by Django 6.0.1 on 2026-02-06 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='Studentage',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='Studentemail',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='Studentname',
        ),
    ]
