# Generated by Django 6.0.1 on 2026-02-06 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_category_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
                ('customerEmail', models.EmailField(max_length=254, unique=True)),
                ('customerPhone', models.CharField(max_length=10)),
                ('customerAddress', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='bankdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=100)),
                ('accountNumber', models.CharField(max_length=20)),
                ('ifscCode', models.CharField(max_length=20)),
                ('customerId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.customer')),
            ],
            options={
                'db_table': 'bankdetails',
            },
        ),
    ]
