# Generated by Django 6.0.1 on 2026-02-06 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_customer_bankdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerName', models.CharField(max_length=100)),
                ('buyerEmail', models.EmailField(max_length=254, unique=True)),
                ('buyerPhone', models.CharField(max_length=10)),
                ('buyerAddress', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'buyer',
            },
        ),
        migrations.CreateModel(
            name='productdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.IntegerField()),
                ('productDescription', models.TextField()),
                ('productStock', models.PositiveIntegerField()),
                ('productColor', models.CharField(max_length=20, null=True)),
                ('productStatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'productdetail',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField()),
                ('orderStatus', models.CharField(max_length=20)),
                ('buyerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.buyer')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.productdetail')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackText', models.TextField()),
                ('feedbackRating', models.IntegerField()),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.order')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
